import type { ReactNode } from 'react'

/**
 * The frame every product reconstruction sits in.
 *
 * No real screenshot of this product exists in the source material, and none
 * was fabricated — not drawn to look photographic, not generated by an image
 * model. What is inside this frame is a rebuild of a screen's information
 * hierarchy in the site's own tokens, with synthetic data.
 *
 * The label is therefore not decoration and not modesty. It is the difference
 * between a reconstruction and a lie, and it renders above the artifact rather
 * than under it so that nobody meets the pixels first.
 *
 * `device` draws a phone shell, and is only worth its weight when the device
 * is part of the argument.
 */
export function Reconstruction({
  children,
  title,
  note,
  device = false,
}: {
  children: ReactNode
  /** What screen this is. */
  title: string
  /** What the reader should look at. */
  note?: string
  device?: boolean
}) {
  return (
    <div className="wide-block my-5">
      <div className="card overflow-hidden">
        <div className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1 border-b border-[var(--color-line)] bg-[var(--color-wash)] px-2.5 py-2">
          <span className="eyebrow">{title}</span>
          <span className="eyebrow text-[var(--color-flag)]">
            Reconstructed · all data synthetic
          </span>
        </div>

        <div className="bg-[var(--color-canvas)] p-2.5 sm:p-4">
          {device ? (
            <div className="mx-auto max-w-[19rem] rounded-[var(--radius-lg)] border-2 border-[var(--color-line-strong)] bg-[var(--color-surface)] p-1.5">
              <div className="overflow-hidden rounded-[var(--radius)] border border-[var(--color-line)]">
                {children}
              </div>
            </div>
          ) : (
            <div className="mx-auto max-w-[26rem] overflow-hidden rounded-[var(--radius)] border border-[var(--color-line)] bg-[var(--color-surface)]">
              {children}
            </div>
          )}
        </div>
      </div>

      {note ? (
        <p className="mt-2 text-[length:var(--text-sm)] leading-relaxed text-[var(--color-body)]">
          {note}
        </p>
      ) : null}
      <p className="mt-0.5 text-[length:var(--text-xs)] leading-relaxed text-[var(--color-muted)]">
        Layout and hierarchy accurate; every name, number and date is invented. No real user appears
        here.
      </p>
    </div>
  )
}
